# Generated by Django 2.2.4 on 2019-10-15 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condicion_de_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_de_pago', models.CharField(blank=True, max_length=128, null=True)),
                ('dias', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(blank=True, max_length=128, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=11, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=128, null=True)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('giro', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=64, null=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Comuna')),
                ('condicion_de_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Condicion_de_pago')),
            ],
        ),
    ]
