# Generated by Django 2.2.4 on 2019-10-15 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_auto_20191015_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(blank=True, null=True)),
                ('tipo', models.SmallIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_hora', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Documento_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Documento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Pedido')),
            ],
        ),
    ]
